## Student Marks Prediction using Regression Model

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv('Datasets/Student_Marks.csv')

In [5]:
data.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [9]:
X = data.drop(['Marks'], axis=1)
y = data['Marks']

In [10]:
X.head()

   number_courses  time_study
0               3       4.508
1               4       0.096
2               4       3.133
3               6       7.909
4               8       7.811

In [11]:
y.head()

0    19.202
1     7.734
2    13.811
3    53.018
4    55.299
Name: Marks, dtype: float64

- Now convert `X` and `y` into tensors

In [15]:
import torch

In [16]:
X_tensor = torch.tensor(X.values, dtype=torch.float)
y_tensor = torch.tensor(y.values, dtype=torch.float)

In [18]:
X_tensor[:5]

tensor([[3.0000, 4.5080],
        [4.0000, 0.0960],
        [4.0000, 3.1330],
        [6.0000, 7.9090],
        [8.0000, 7.8110]])

In [19]:
y_tensor[:5]

tensor([19.2020,  7.7340, 13.8110, 53.0180, 55.2990])

- train test split using sklearn

In [25]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X_tensor, y_tensor, test_size=0.2, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([80, 2]), torch.Size([20, 2]), torch.Size([80]), torch.Size([20]))

- Model training - Regression Model

In [33]:
import torch.nn as nn

In [71]:
class Model(nn.Module):
    def __init__(self, input_dim=2, hidden_1=10, hidden_2=20, hidden_3=10, output_dim=1):
        super(Model, self).__init__()

        
        # layers    

        self.fc1 = nn.Linear(input_dim, hidden_1) #input layer

        # hidden state - start 
        self.fc2 = nn.Linear(hidden_1, hidden_2)
        self.relu1 = nn.ReLU()
        self.do1 = nn.Dropout(0.2)
        

        self.fc3 = nn.Linear(hidden_2, hidden_3)
        self.relu2 = nn.ReLU()
        self.do2 = nn.Dropout(0.1)

        self.fc4 = nn.Linear(hidden_3, output_dim)

    def forward(self, x):
        x = self.fc1(x)

        x = self.fc2(x)
        x = self.relu1(x)
        x = self.do1(x)
        

        x = self.fc3(x)
        x = self.relu2(x)
        x = self.do2(x)
        
        x = self.fc4(x)

        return x

In [72]:
model = Model()
model

Model(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=20, bias=True)
  (relu1): ReLU()
  (do1): Dropout(p=0.2, inplace=False)
  (fc3): Linear(in_features=20, out_features=10, bias=True)
  (relu2): ReLU()
  (do2): Dropout(p=0.1, inplace=False)
  (fc4): Linear(in_features=10, out_features=1, bias=True)
)

In [73]:
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [74]:
X_train.shape

torch.Size([80, 2])

In [75]:
epoches = 101 

for epoch in range(epoches):
    model.train()

    out = model(X_train)
    loss = loss_function(out, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epoch: ", epoch, "Loss: ", loss.item())

Epoch:  0 Loss:  715.443115234375
Epoch:  10 Loss:  698.7449340820312
Epoch:  20 Loss:  681.4622802734375
Epoch:  30 Loss:  657.2459106445312
Epoch:  40 Loss:  625.7147216796875
Epoch:  50 Loss:  587.7413940429688
Epoch:  60 Loss:  525.9776611328125
Epoch:  70 Loss:  464.7449951171875
Epoch:  80 Loss:  393.8188171386719
Epoch:  90 Loss:  316.1276550292969
Epoch:  100 Loss:  264.18817138671875

/home/aishwarya/Downloads/Notes/PyTorch_Notes/Notebooks/.venv/lib/python3.13/site-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([80])) that is different to the input size (torch.Size([80, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

- Lets predict

In [102]:
My_Data = torch.tensor([[1, 81.5]], dtype=torch.float)

In [103]:
model.eval()
with torch.no_grad():
    out = model(My_Data)

In [104]:
out

tensor([[100.8426]])